[package]
name = "tutorial3-pipeline"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.22"
shaderc = "0.6"
cgmath = "0.17"
wgpu = "0.6"
futures = "0.3"

[[bin]]
name = "tutorial3-pipeline"
path = "src/main.rs"

[[bin]]
name = "tutorial3-challenge"
path = "src/challenge.rs"