[workspace]
resolver = "2"
members = [
    # # beginner tutorials
    "code/beginner/*",

    # # intermediate tutorials
    "code/intermediate/*",

    # # showcase
    "code/showcase/*",
]
exclude = [
    "code/showcase/imgui-demo",
    "code/showcase/pong",
]