[workspace]
resolver = "2"
members = [
    # # beginner tutorials
    # "code/beginner/*",

    # # intermediate tutorials
    # "code/intermediate/*",

    # # showcase
    # "code/showcase/*",
    "code/beginner/tutorial2-swapchain"
]
exclude = [
    "code/showcase/imgui-demo",
    "code/showcase/pong",
]