[package]
name = "framework"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.4"
winit = "0.20.0"
shaderc = "0.6"
cgmath = "0.17.0"
failure = "0.1"
futures = "0.3.4"
tobj = "1.0.0"
wgpu = "0.5.0"
bytemuck = "1.2.0"