[package]
name = "tutorial9-models"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.22"
shaderc = "0.6"
cgmath = "0.17"
failure = "0.1"
tobj = "1.0.0"
wgpu = "0.5.0"
futures = "0.3.4"
bytemuck = "1.2.0"

[[bin]]
name = "tutorial9-models"
path = "src/main.rs"


# [[bin]]
# name = "tutorial9-challenge"
# path = "src/challenge.rs"